### ISSUE TITLE
The OpenSSL included in package is too old.

### ISSUE THREAD

**Issue by gnattu** [iuscommunity-pkg/stunnel5u#5]
This repo is compiled against openssl 1.0.2k, which is already EOF(Support for OpenSSL 1.0.2 ended at  31st December 2019).  An upgrade to 1.1.1 is necessary for both security and feature.

**Comment by carlwgeorge** [comment]
IUS builds our packages against stock libraries whenever possible.  This includes EL7's openssl 1.0.2k.  The upstream EOL date for the software is immaterial, because Red Hat is maintaining this package with security backports until the EOL of EL7 in 2024-06-30.

https://access.redhat.com/security/updates/backporting
https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates
